### ISSUE TITLE
Messages doesn't allow parameters 4.3

### ISSUE THREAD

**Issue by CreoCoding** [plivo/plivo-php#136]
Was working fine in 4.1, but since I upgraded I am not only getting the wrong amount of messages if left with out any parameters, but including some results in tons of errors. For instance:

`
   $response = $client->messages->list(
     array(
	'message_direction' => 'outbound',
	'offset' => $offset,
	'message_time__gte' => $fromTime,
	'message_time__lte' => $toTime,
      )
    );
`

Including any or all of those gives me:

[Wed Jul 24 17:19:49.965662 2019] [fcgid:warn] [pid 27461] [client 1.2.3.4.5.6] mod_fcgid: stderr: PHP Warning:  Invalid argument supplied for foreach() in .../api/vendor/plivo/php-sdk/src/Plivo/Resources/Message/MessageInterface.php on line 86, referer: /history.php?log_id=19&type=phone

[Wed Jul 24 17:19:49.965675 2019] [fcgid:warn] [pid 27461] [client 1.2.3.4.5.6] mod_fcgid: stderr: PHP Notice:  Undefined index: meta in .../api/vendor/plivo/php-sdk/src/Plivo/Resources/Message/MessageInterface.php on line 92, referer: history.php?log_id=19&type=phone

[Wed Jul 24 17:19:49.965678 2019] [fcgid:warn] [pid 27461] [client 1.2.3.4.5.6] mod_fcgid: stderr: PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Plivo\\Resources\\ResourceList::__construct() must be of the type array, null given, called in .../api/vendor/plivo/php-sdk/src/Plivo/Resources/Message/MessageList.php on line 24 and defined in .../api/vendor/plivo/php-sdk/src/Plivo/Resources/ResourceList.php:45, referer: history.php?log_id=19&type=phone

[Wed Jul 24 17:19:49.965681 2019] [fcgid:warn] [pid 27461] [client 1.2.3.4.5.6] mod_fcgid: stderr: Stack trace:, referer: history.php?log_id=19&type=phone

[Wed Jul 24 17:19:49.965683 2019] [fcgid:warn] [pid 27461] [client 1.2.3.4.5.6] mod_fcgid: stderr: #0 .../api/vendor/plivo/php-sdk/src/Plivo/Resources/Message/MessageList.php(24): Plivo\\Resources\\ResourceList->__construct(Object(Plivo\\BaseClient), NULL, Array), referer: /history.php?log_id=19&type=phone

[Wed Jul 24 17:19:49.965686 2019] [fcgid:warn] [pid 27461] [client 1.2.3.4.5.6] mod_fcgid: stderr: #1 .../api/vendor/plivo/php-sdk/src/Plivo/Resources/Message/MessageInterface.php(92): Plivo\\Resources\\Message\\MessageList->__construct(Object(Plivo\\BaseClient), NULL, Array), referer: history.php?log_id=19&type=phone

[Wed Jul 24 17:19:49.965689 2019] [fcgid:warn] [pid 27461] [client 1.2.3.4.5.6] mod_fcgid: stderr: #2 [internal function]: Plivo\\Resources\\Message\\MessageInterface->getList(Array), referer: history.php?log_id=19&type=phone

[Wed Jul 24 17:19:49.965692 2019] [fcgid:warn] [pid 27461] [client 1.2.3.4.5.6] mod_fcgid: stderr: #3 .../api/vendor/plivo/php-sdk/src/Plivo/Resources/ResourceInterface.php(65): call_user_func_array(Array, Array), referer: history.php?log_id=19&type=phone

[Wed Jul 24 17:19:49.965694 2019] [fcgid:warn] [pid 27461] [client 1.2.3.4.5.6] mod_fcgid: stderr: #4 /home/.../public_html/new/deliver in .../api/vendor/plivo/php-sdk/src/Plivo/Resources/ResourceList.php on line 45, referer: history.php?log_id=19&type=phone

**Comment by CreoCoding** [comment]
This may be all set now switching over to PHP 7.1.
